### ISSUE TITLE
Can not download any anime in 1080, even if my account is premium.

### ISSUE THREAD

**Issue by ilukasschneider** [r33int/crunchyrollDownloader#1]
Screens:

![screen shot 2018-03-30 at 17 30 10](https://user-images.githubusercontent.com/18196954/38143311-30408a10-3440-11e8-8ea8-128ad3060271.png)
![screen shot 2018-03-30 at 17 31 06](https://user-images.githubusercontent.com/18196954/38143313-32a80670-3440-11e8-98e9-10b85d62e93a.png)

**Comment by skid9000** [comment]
Are you sure that your cookies.txt is valid ? When youtube-dl stop at 480p, generally, it means that or the account is not premium or that the cookies.txt is invalid.

If you are not sure how to make your cookies.txt properly, you can try this https://github.com/skid9000/CrunchyrollAuth

<img src="https://puush.tuto-craft.com/1n6V1r.png"></img>

**Comment by r33int** [comment]
Hi, is your problem solved?

**Comment by ilukasschneider** [comment]
Sry for answering so late...

It actually did fix my problem, thank you!

Nevertheless I wanted to ask if there will be some kind of merging of the subs and the .mp4 in the future? The download of a whole series with a link like: "http://www.crunchyroll.com/naruto" would also be a great feature to have.

**Comment by r33int** [comment]
I will see if I can add this, but, as far as I know, it will need to convert the video from MP4 to MKV, so encoding will be necessary, which may take a while for the end user. However, I think I can still implement it as a choice.

About downloading the whole series, you can! Input the series's URL and it should download all episodes! I will add a notice about that.

By the way, I am completely rewriting the script right now, stay tuned!  😉
