### ISSUE TITLE
missing video quality option: "best"

### ISSUE THREAD

**Issue by ilukasschneider** [r33int/crunchyrollDownloader#2]
When trying to download a whole anime-series which has some old episodes in 480p but also some new episodes in 1080p there is no such option to choose the best quality possible. 

When chossing 1080p I get an error when downloading the old episodes.

**Comment by r33int** [comment]
will be added in next update, thanks!

**Comment by r33int** [comment]
The new update is out and it introduces language select, and best quality setting. Also, the script has beenn rewritten from scratch to make it easier to maintain. Download it by pulling the repository, or download latest release! https://github.com/r33int/crunchyrollDownloader/releases

Hope you appreciate it 😄

**Comment by ilukasschneider** [comment]
You are the best! Thank you so much! 👍 👍 👍
