### ISSUE TITLE
me again: cookie.txt problem in newest version

### ISSUE THREAD

**Issue by ilukasschneider** [r33int/crunchyrollDownloader#3]
same cookies.txt did run in previous version but the new version seems to have a problem:

<img width="1072" alt="screen shot 2018-04-02 at 14 05 01" src="https://user-images.githubusercontent.com/18196954/38195691-1af9434a-367f-11e8-90a6-3f9bfe1a40f9.png">

edit: it seems u just have a typo in line 39...fixing it leads to the console printing "test" ?!
<img width="214" alt="screen shot 2018-04-02 at 14 12 57" src="https://user-images.githubusercontent.com/18196954/38195834-f901c90a-367f-11e8-81ff-bb57a233d803.png">

**Comment by r33int** [comment]
My bad, seems like I accidentally uploaded an old, unfinished file. I am going to do one more release with the correct file.

**Comment by r33int** [comment]
Just uploaded the release, sorry about that.
