### ISSUE TITLE
Is there a way to filter the download?

### ISSUE THREAD

**Issue by ilukasschneider** [r33int/crunchyrollDownloader#4]
When trying to load a series with 100+ episodes the script just ends itself before downloading all of them. Is there a way to change something to get for example every episode > 200?

**Comment by r33int** [comment]
Can you provide terminal transcript?

**Comment by ilukasschneider** [comment]
Sry, but what exactly do you mean with that? The script just ends and the console gets cleared.

**Comment by r33int** [comment]
will look at it tomorrow ;)

**Comment by ilukasschneider** [comment]
No worrys, take your time.
Btw sorry for issuing your script multiple times a day ;)

**Comment by r33int** [comment]
Hi. I am now working on the issue. Can you please give me a link of a series that fails to download?

**Comment by ilukasschneider** [comment]
**I do not think that the problem is specific to a series!** Tried downloading HunterXHunter, Naruto and Naruto Shippuden but neither of them finished before some kind of error occurs. 

I do not think that there is a problem in your code, but rather something on Crunchyroll´s side (read some descriptions of other Crunchyroll-Downlaoder and one stated that **Crunchyroll sometimes makes problems when trying to download content from their server**).

**Comment by r33int** [comment]
I tried downloading a 100+ episodes series, and it seems to work to me. I think there's not much I could do about this, sorry... That's also weird you don't get any logs at all.
